version: '3.8'
services:
  movies:
    image: akshaykumar0007/movies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: akshaykumar0007/train:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: akshaykumar0007/dth:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: akshaykumar0007/recharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
